from PySide6.QtWidgets import *
from PySide6.QtCore import *
from PySide6.QtGui import *
import os
def add_toolbar(self):
    toolbar = QToolBar()
    toolbar.setMovable(False)
    toolbar.setIconSize(QSize(20,20))
    self.addToolBar(toolbar)
    back_button = QAction("Back",self)
    back_button.triggered.connect(self.webview.back)
    back_button.setIcon(QIcon("images/left.png"))
    toolbar.addAction(back_button)
    forward_button = QAction("Forward",self)
    forward_button.triggered.connect(self.webview.forward)
    forward_button.setIcon(QIcon("images/right.png"))
    toolbar.addAction(forward_button)
    reload_button = QAction("Reload",self)
    reload_button.triggered.connect(self.webview.reload)
    reload_button.setIcon(QIcon("images/reload.png"))
    toolbar.addAction(reload_button)
    home_button = QAction("Home",self)
    home_button.setIcon(QIcon("images/home.png"))
    current_dir = os.path.dirname(os.path.abspath(__file__))
    home_button.triggered.connect(lambda:self.webview.setUrl("http://google.com"))
    toolbar.addAction(home_button)
    self.url_bar = QLineEdit()
    self.url_bar.returnPressed.connect(lambda:self.webview.setUrl(QUrl.fromUserInput("http://"+self.url_bar.text())))
    self.url_bar.setPlaceholderText("Enter URL")
    self.url_bar.setClearButtonEnabled(True)
    self.webview.urlChanged.connect(lambda url:self.url_bar.setText(url.toString()))
    toolbar.addWidget(self.url_bar)
    dots_button = QAction("Options",self)
    dots_button.triggered.connect(self.webview.reload)
    dots_button.setIcon(QIcon("images/dots.png"))
    menu = QMenu()
    menu.addAction("About")
    menu.addAction("Downloads")
    menu.addSeparator()
    exit_action = QAction("Exit",self)
    exit_action.triggered.connect(QApplication.instance().quit)
    menu.addAction(exit_action)
    dots_button.triggered.connect(lambda:menu.exec(QCursor.pos()))
    toolbar.addAction(dots_button)